services:
  postgres_warehouse:
    image: postgres:14
    container_name: postgres_warehouse
    environment:
      POSTGRES_USER: warehouse_user
      POSTGRES_PASSWORD: warehouse_pass
      POSTGRES_DB: warehouse_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_warehouse_data:/var/lib/postgresql/data

volumes:
  postgres_warehouse_data: